### ISSUE TITLE
feat: `'experimental_connect'` restore address/credentialId from storage

### ISSUE THREAD

**Issue by tmm** [ithacaxyz/porto#14]
When connecting with `'experimental_connect'`, attempt to restore `address` and `credentialId` from storage to eliminate [extra WebAuthn prompt](https://github.com/ithacaxyz/porto/blob/main/src/internal/accountDelegation.ts#L408-L418).

### TODO

- [ ] Persist `address` and `credentialId` on successful `'experimental_createAccount`, `'experimental_connect'`, etc.
- [ ] On subsequent calls of `'experimental_connect'`, pass in persisted `address` and `credentialId` to optimistically connect in a single prompt.
- [ ] Handle errors if `address` and/or `credentialId` are invalid (don't match, signer doesn't have access, etc.)

**Comment by frankudoags** [comment]
Can I work on this please?

**Comment by tmm** [comment]
@frankudoags go for it! In general anyone is allowed to work on anything.

If it's something major, we ask that you run it by us first so you aren't wasting time, but since this is a ["good first issue"](https://github.com/ithacaxyz/porto/issues?q=state%3Aopen+label%3A%22good+first+issue%22) no need to ask.

We also don't usually assign issues to folks since we don't want people waiting around so whoever gets a solid PR in first is more likely to get it merged.

**Comment by 0x471** [comment]
I've just opened https://github.com/ithacaxyz/porto/pull/18 to address this issue.

Please review when you have a chance. Let me know if you'd like me to make any adjustments.

**Comment by frankudoags** [comment]
Hello there @0x471 

Your work on https://github.com/ithacaxyz/porto/pull/15 Looks good, persisting with local storage, I also have https://github.com/ithacaxyz/porto/pull/15 open to address this issue and awaiting review, you may want to take a look as well. I added the address and credential id to the zustand state directly instead.
